# Generated by Django 4.1.4 on 2022-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_question_number_wa_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_wa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
