# Generated by Django 4.1.4 on 2023-01-23 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_question_point_alter_question_number_wa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
